version: "3.7"

services:
  php:
    image: ghcr.io/rene-bos/iw-ghdw-php:8.1-ci-latest
    volumes:
      - .:/app

  web:
    image: ghcr.io/rene-bos/iw-ghdw-nginx:symfony-latest
    volumes:
      - .:/app
    ports:
      - "6001:80"
