apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-{{ .Release.Name }}
  labels:
    app: {{ .Values.name }}-{{ .Release.Name }}
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: {{ .Values.name }}-{{ .Release.Name }}
