apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-{{ .Release.Name }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Values.name }}-{{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}-{{ .Release.Name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/frontend-configmap.yaml") . | sha256sum }}
    spec:
      containers:
        - name: php
          image: {{ required "Value `image.registry` is required." .Values.image.registry }}/iw-ghdw-app-php:{{ required "Value `image.tag` is required." .Values.image.tag }}
          envFrom:
            - configMapRef:
                name: "{{ .Values.name }}-{{ .Release.Name }}-config"
        - name: web
          image: {{ required "Value `image.registry` is required." .Values.image.registry }}/iw-ghdw-app-web:{{ required "Value `image.tag` is required." .Values.image.tag }}
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /hello
              port: 80
          readinessProbe:
            httpGet:
              path: /hello
              port: 80
