apiVersion: apps/v1
kind: Deployment
metadata:
  name: iw-ghdw-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iw-ghdw-app
      tier: frontend
  template:
    metadata:
      labels:
        app: iw-ghdw-app
        tier: frontend
    spec:
      containers:
        - name: php
          image: localhost:32000/iw-ghdw-app-php:v10
          env:
            - name: APP_ENV
              value: prod
        - name: web
          image: localhost:32000/iw-ghdw-app-web:v5
          env:
            - name: APP_ENV
              value: prod
          ports:
            - containerPort: 80
