name: Build Docker images

on:
  push:
    branches:
      - main
      - release-*
    tags:
      - v*

env:
  REGISTRY: ghcr.io

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci.yml

  build-source:
    name: Build source
    needs: ci
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/rene-bos/iw-ghdw-php:8.1-ci-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install PHP dependencies
        run: composer install --no-dev --no-interaction --optimize-autoloader

      - name: Zip build artifact
        run: zip -r build-source.zip .

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-source
          path: build-source.zip
          retention-days: 7

  build-and-push-php:
    name: Build & push PHP image
    needs: build-source
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      IMAGE_NAME: rene-bos/iw-ghdw-app-php
      IMAGE_TITLE: IW GHDW App | PHP
    steps:
      - name: Download build source
        uses: actions/download-artifact@v3
        with:
          name: build-source
          
      - name: Unzip build source artifact
        run: |
          unzip build-source.zip -d .
          rm build-source.zip

      - name: Log in to container registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Extract metadata (tags, labels) for Docker
        id: meta-php
        uses: docker/metadata-action@v4.0.1
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: |
            latest=auto
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
            type=edge,branch=main
          labels: |
            - org.opencontainers.image.title=${{ env.IMAGE_TITLE }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2.10.0
        with:
          file: ./infrastructure/docker/php/Dockerfile
          context: .
          push: true
          tags: ${{ steps.meta-php.outputs.tags }}
          labels: ${{ steps.meta-php.outputs.labels }}

  build-and-push-web:
    name: Build & push web image
    needs: build-source
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      IMAGE_NAME: rene-bos/iw-ghdw-app-web
      IMAGE_TITLE: IW GHDW App | Web
    steps:
      - name: Download build source
        uses: actions/download-artifact@v3
        with:
          name: build-source
          
      - name: Unzip build source artifact
        run: |
          unzip build-source.zip -d .
          rm build-source.zip

      - name: Log in to container registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Extract metadata (tags, labels) for Docker
        id: meta-web
        uses: docker/metadata-action@v4.0.1
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: |
            latest=auto
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
            type=edge,branch=main
          labels: |
            - org.opencontainers.image.title=${{ env.IMAGE_TITLE }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2.10.0
        with:
          file: ./infrastructure/docker/web/Dockerfile
          context: .
          push: true
          tags: ${{ steps.meta-web.outputs.tags }}
          labels: ${{ steps.meta-web.outputs.labels }}
