name: deploy
on:
  push:
  workflow_dispatch: { }

env:
  ACR_RESOURCE_GROUP: aks-test
  AZURE_CONTAINER_REGISTRY: reneakstest
  CHART_OVERRIDE_PATH: ./infrastructure/helm/values.yaml
  CHART_OVERRIDES: image.registry=reneakstest.azurecr.io,image.tag=${{ github.sha }}
  CHART_PATH: ./infrastructure/helm
  CLUSTER_NAME: aks-test
  CLUSTER_RESOURCE_GROUP: aks-test
  CONTAINER_NAME_WEB: iw-ghdw-app-web
  CONTAINER_NAME_PHP: iw-ghdw-app-php
  VERSION_NAME: ${{ vars.github.ref_name }}

jobs:
  buildImages:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    environment:
      name: reviewapps
    steps:
      - name: Debug
        run: |
          echo "Env: ${{ env.GITHUB_REF_NAME }}"
          echo "Var: ${{ vars.github.ref_name  }}"
          echo "Env: ${{ env.VERSION_NAME }}"
          echo "Direct env: ${VERSION_NAME}"
          echo "Modified env: ${VERSION_NAME,,}"
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      - name: Install PHP dependencies
        run: composer install --no-dev --no-interaction --optimize-autoloader

      - name: Azure login
        uses: azure/login@v1.4.3
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      - name: Add version number to source files
        run: sed -i 's/{{VERSION}}/${{ env.GITHUB_REF_NAME}}/' src/Controller/InfoController.php
      - name: Build and push image to ACR (${{ env.CONTAINER_NAME_WEB }})
        run: az acr build --image ${{ env.CONTAINER_NAME_WEB }}:${{ github.sha }} --registry ${{ env.AZURE_CONTAINER_REGISTRY }} -g ${{ env.ACR_RESOURCE_GROUP }} -f ./infrastructure/docker/web/Dockerfile ./
      - name: Build and push image to ACR (${{ env.CONTAINER_NAME_PHP }})
        run: az acr build --image ${{ env.CONTAINER_NAME_PHP }}:${{ github.sha }} --registry ${{ env.AZURE_CONTAINER_REGISTRY }} -g ${{ env.ACR_RESOURCE_GROUP }} -f ./infrastructure/docker/php/Dockerfile ./
  
  deploy:
    permissions:
      actions: read
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    needs:
      - buildImages
    environment:
      name: reviewapps
      url: http://{${ env.GITHUB_REF_NAME }}.review.iw-ghdw-app.local/info
    steps:
      - uses: actions/checkout@v3
      - uses: azure/login@v1.4.3
        name: Azure login
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      - uses: azure/use-kubelogin@v1
        name: Set up kubelogin for non-interactive login
        with:
          kubelogin-version: v0.0.25
      - uses: azure/aks-set-context@v3
        name: Get K8s context
        with:
          admin: "false"
          cluster-name: ${{ env.CLUSTER_NAME }}
          resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}
          use-kubelogin: "true"
      - name: Deploy application
        run: helm upgrade --wait -i  --create-namespace --namespace reviewapps -f ${{ env.CHART_OVERRIDE_PATH }} --set ${{ env.CHART_OVERRIDES }} ${{ env.GITHUB_REF_NAME }} ${{ env.CHART_PATH }}
