# This workflow automatically updates the PHPStan baseline if our `main` branch has errors.
# The automated update of the baseline is only needed because the PHPStan check is not (yet) required for a
# pull request. Once the check is required we can remove this workflow as no errors can be merged to the main branch
# anymore.

name: PHPStan baseline updater
on:
  push:
    branches:
      - main

jobs:
  update-baseline:
    name: Update baseline
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      -  name: Setup PHP
         uses: shivammathur/setup-php@d30ad8b1843ace22e6698ab99bbafaa747b6bd0d # 2.24.0
         with:
           php-version: 8.1

      - name: Install dependencies
        run: composer install --no-interaction --optimize-autoloader

      - name: Generate baseline
        run: composer run-script phpstan -- --generate-baseline

      - name: Create pull request if baseline has been changes
        id: create-pull-request
        uses: peter-evans/create-pull-request@2b011faafdcbc9ceb11414d64d0573f37c774b04 # v4.2.3
        with:
          add-paths: ./phpstan-baseline.neon
          commit-message: Automated update of PHPStan baseline
          branch: automated-phpstan-baseline-update
          title: Automated update of PHPStan baseline
          body: |
            The automated update of the PHPStan baseline is only needed because the PHPStan check is not (yet) required 
            for a pull request. Once the check is required we can remove this automated update as no errors can be 
            merged to the main branch anymore.
          reviewers: |
            rene-bos
      - name: Show created pull request (if any)
        if: ${{ steps.create-pull-request.outputs.pull-request-number }}
        run: |
          echo "Pull request number: ${{ steps.create-pull-request.outputs.pull-request-number }}"
          echo "Pull request URL: ${{ steps.create-pull-request.outputs.pull-request-url }}"
